export const metadata = {
  title: "dashboard",
  description: "Dashboard Generated by create next app",
};

const Dashboard = () => {
  return (
    <div className="flex">
      <h1>This is dashboard page</h1>
    </div>
  );
};

export default Dashboard;
